.PHONY: clean All

All:
	@echo "----------Building project:[ SnakeGame - Debug ]----------"
	@cd "SnakeGame" && "$(MAKE)" -f  "SnakeGame.mk"
clean:
	@echo "----------Cleaning project:[ SnakeGame - Debug ]----------"
	@cd "SnakeGame" && "$(MAKE)" -f  "SnakeGame.mk" clean
